apiVersion: v1
kind: Secret
metadata:
  name: github-bot-token
  namespace: github-bot
type: Opaque
data:
  github_token: # add your gh token
  zenhub_token: # add your zenhub token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-bot-flask-auth
  namespace: github-bot
type: kubernetes.io/basic-auth
data:
  password: # add flask username
  username: # add falsk password
