apiVersion: v1
kind: Service
metadata:
  name: github-bot
  namespace: github-bot
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: github-bot
  sessionAffinity: None
  type: NodePort
